import React from 'react'
import './Template.css'

function Template() {
  return (
    <div className='maincontainer'>
      <div className='paperh'>
      <div className='header'>
          <h3>Privacy Policy for </h3>
        </div>
      
      <div className='paper'>
        
        <div className='title'>
          <div className='subh'>
            <h1>Privacy Policy</h1>          
          </div>
        </div>
        <div className='content'>
          <div className='cphara'>
            <p>Last updated: June 02, 2024</p>
            <p>This Privacy Policy describes Our policies and procedures on the collection,
               use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>

            <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information 
              in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.</p>
          </div>
          <div className='cphara'>
            <div className='ctitle'>
              <h2>Interpretation and Definitions</h2>
            </div>
            <div className='ctitle'>
              <h4>Interpretation</h4>
            </div>
            <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions 
            shall have the same meaning regardless of whether they appear in singular or in plural.</p>
            <div className='ctitle'>
              <h4>Definitions</h4>
            </div>
            <p>For the purposes of this Privacy Policy:</p>
            <div className='list'>
            <ul>
                <li><strong>Account</strong>means a unique account created for You to access our Service or parts of our Service.</li>
                <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, 
                where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                <li><strong>Application</strong> refers to VoiceEase, the software program provided by the Company.</li>
                <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to VoiceEase.</li>
                <li><strong>Country</strong> refers to: Sri Lanka</li>
                <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                <li><strong>Personal</strong> Data is any information that relates to an identified or identifiable individual.</li>
                <li><strong>Service</strong> refers to the Application.</li>
                <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the 
                Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
                <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
              </ul>
            </div>
          </div>
          <div className='cphara'>
            <div className='ctitle'>
              <h2>Collecting and Using Your Personal Data</h2>
            </div>
            <div className='ctitle'>
              <h4>Types of Data Collected</h4>
            </div>
            <div className='ctitle'>
              <h5>Personal Data</h5>
            </div>
            <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. 
              Personally identifiable information may include, but is not limited to:</p>
              <div className='list'>
                <ul>
                  <li>Usage Data</li>
                </ul>
              </div>
              <div className='ctitle'>
              <h5>Usage Data</h5>
            </div>
            <p>Usage Data is collected automatically when using the Service.</p>
            <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, 
              unique device identifiers and other diagnostic data.</p>
            <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, 
              unique device identifiers and other diagnostic data.</p>
            <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
            <p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>
            <div className='ctitle'>
              <h4>Use of Your Personal Data</h4>
            </div>
            <p>The Company may use Personal Data for the following purposes:</p>
            <div className='list'>
            <ul>
                <li><strong>To provide and maintain our Service,</strong> including to monitor the usage of our Service.</li>
                <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, 
                where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                <li><strong>Application</strong> refers to VoiceEase, the software program provided by the Company.</li>
                <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to VoiceEase.</li>
                <li><strong>Country</strong> refers to: Sri Lanka</li>
                <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                <li><strong>Personal</strong> Data is any information that relates to an identified or identifiable individual.</li>
                <li><strong>Service</strong> refers to the Application.</li>
                <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the 
                Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
                <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
              </ul>
            </div>
          </div>

        </div>
      </div>
      </div>
    </div>
  )
}

export default Template